var leeicons = [
    'lee-ion-ionic', 'lee-ion-arrow-up-a', 'lee-ion-arrow-right-a', 'lee-ion-arrow-down-a',
    'lee-ion-arrow-left-a', 'lee-ion-arrow-up-b', 'lee-ion-arrow-right-b', 'lee-ion-arrow-down-b',
    'lee-ion-arrow-left-b', 'lee-ion-arrow-up-c', 'lee-ion-arrow-right-c', 'lee-ion-arrow-down-c',
    'lee-ion-arrow-left-c', 'lee-ion-arrow-return-right', 'lee-ion-arrow-return-left',
    'lee-ion-arrow-swap', 'lee-ion-arrow-shrink', 'lee-ion-arrow-expand', 'lee-ion-arrow-move',
    'lee-ion-arrow-resize', 'lee-ion-chevron-up', 'lee-ion-chevron-right', 'lee-ion-chevron-down',
    'lee-ion-chevron-left', 'lee-ion-navicon-round', 'lee-ion-navicon', 'lee-ion-drag', 'lee-ion-log-in',
    'lee-ion-log-out', 'lee-ion-checkmark-round', 'lee-ion-checkmark', 'lee-ion-checkmark-circled',
    'lee-ion-close-round', 'lee-ion-close', 'lee-ion-close-circled', 'lee-ion-plus-round',
    'lee-ion-plus', 'lee-ion-plus-circled', 'lee-ion-minus-round', 'lee-ion-minus',
    'lee-ion-minus-circled', 'lee-ion-information', 'lee-ion-information-circled', 'lee-ion-help',
    'lee-ion-help-circled', 'lee-ion-backspace-outline', 'lee-ion-backspace', 'lee-ion-help-buoy',
    'lee-ion-asterisk', 'lee-ion-alert', 'lee-ion-alert-circled', 'lee-ion-refresh', 'lee-ion-loop',
    'lee-ion-shuffle', 'lee-ion-home', 'lee-ion-search', 'lee-ion-flag', 'lee-ion-star', 'lee-ion-heart',
    'lee-ion-heart-broken', 'lee-ion-gear-a', 'lee-ion-gear-b', 'lee-ion-toggle-filled',
    'lee-ion-toggle', 'lee-ion-settings', 'lee-ion-wrench', 'lee-ion-hammer', 'lee-ion-edit',
    'lee-ion-trash-a', 'lee-ion-trash-b', 'lee-ion-document', 'lee-ion-document-text',
    'lee-ion-clipboard', 'lee-ion-scissors', 'lee-ion-funnel', 'lee-ion-bookmark', 'lee-ion-email',
    'lee-ion-email-unread', 'lee-ion-folder', 'lee-ion-filing', 'lee-ion-archive', 'lee-ion-reply',
    'lee-ion-reply-all', 'lee-ion-forward', 'lee-ion-share', 'lee-ion-paper-airplane', 'lee-ion-link',
    'lee-ion-paperclip', 'lee-ion-compose', 'lee-ion-briefcase', 'lee-ion-medkit', 'lee-ion-at',
    'lee-ion-pound', 'lee-ion-quote', 'lee-ion-cloud', 'lee-ion-upload', 'lee-ion-more', 'lee-ion-grid',
    'lee-ion-calendar', 'lee-ion-clock', 'lee-ion-compass', 'lee-ion-pinpoint', 'lee-ion-pin', 'lee-ion-navigate',
    'lee-ion-location', 'lee-ion-map', 'lee-ion-lock-combination', 'lee-ion-locked', 'lee-ion-unlocked',
    'lee-ion-key', 'lee-ion-arrow-graph-up-right', 'lee-ion-arrow-graph-down-right', 'lee-ion-arrow-graph-up-left',
    'lee-ion-arrow-graph-down-left', 'lee-ion-stats-bars', 'lee-ion-connection-bars', 'lee-ion-pie-graph',
    'lee-ion-chatbubble', 'lee-ion-chatbubble-working', 'lee-ion-chatbubbles', 'lee-ion-chatbox', 'lee-ion-chatbox-working',
    'lee-ion-chatboxes', 'lee-ion-person', 'lee-ion-person-add', 'lee-ion-person-stalker', 'lee-ion-woman',
    'lee-ion-man', 'lee-ion-female', 'lee-ion-male', 'lee-ion-transgender', 'lee-ion-fork', 'lee-ion-knife',
    'lee-ion-spoon', 'lee-ion-soup-can-outline', 'lee-ion-soup-can', 'lee-ion-beer', 'lee-ion-wineglass', 'lee-ion-coffee',
    'lee-ion-icecream', 'lee-ion-pizza', 'lee-ion-power', 'lee-ion-mouse', 'lee-ion-battery-full', 'lee-ion-battery-half',
    'lee-ion-battery-low', 'lee-ion-battery-empty', 'lee-ion-battery-charging', 'lee-ion-wifi', 'lee-ion-bluetooth',
    'lee-ion-calculator', 'lee-ion-camera', 'lee-ion-eye', 'lee-ion-eye-disabled', 'lee-ion-flash', 'lee-ion-flash-off',
    'lee-ion-qr-scanner', 'lee-ion-image', 'lee-ion-images', 'lee-ion-wand', 'lee-ion-contrast', 'lee-ion-aperture',
    'lee-ion-crop', 'lee-ion-easel', 'lee-ion-paintbrush', 'lee-ion-paintbucket', 'lee-ion-monitor', 'lee-ion-laptop',
    'lee-ion-ipad', 'lee-ion-iphone', 'lee-ion-ipod', 'lee-ion-printer', 'lee-ion-usb', 'lee-ion-outlet', 'lee-ion-bug',
    'lee-ion-code', 'lee-ion-code-working', 'lee-ion-code-download', 'lee-ion-fork-repo', 'lee-ion-network',
    'lee-ion-pull-request', 'lee-ion-merge', 'lee-ion-xbox', 'lee-ion-playstation', 'lee-ion-steam', 'lee-ion-closed-captioning',
    'lee-ion-videocamera', 'lee-ion-film-marker', 'lee-ion-disc', 'lee-ion-headphone', 'lee-ion-music-note',
    'lee-ion-radio-waves', 'lee-ion-speakerphone', 'lee-ion-mic-a', 'lee-ion-mic-b', 'lee-ion-mic-c', 'lee-ion-volume-high',
    'lee-ion-volume-medium', 'lee-ion-volume-low', 'lee-ion-volume-mute', 'lee-ion-levels', 'lee-ion-play', 'lee-ion-pause',
    'lee-ion-stop', 'lee-ion-record', 'lee-ion-skip-forward', 'lee-ion-skip-backward', 'lee-ion-eject', 'lee-ion-bag',
    'lee-ion-card', 'lee-ion-cash', 'lee-ion-pricetag', 'lee-ion-pricetags', 'lee-ion-thumbsup', 'lee-ion-thumbsdown',
    'lee-ion-happy-outline', 'lee-ion-happy', 'lee-ion-sad-outline', 'lee-ion-sad', 'lee-ion-bowtie', 'lee-ion-tshirt-outline',
    'lee-ion-tshirt', 'lee-ion-trophy', 'lee-ion-podium', 'lee-ion-ribbon-a', 'lee-ion-ribbon-b', 'lee-ion-university',
    'lee-ion-magnet', 'lee-ion-beaker', 'lee-ion-erlenmeyer-flask', 'lee-ion-egg', 'lee-ion-earth', 'lee-ion-planet',
    'lee-ion-lightbulb', 'lee-ion-cube', 'lee-ion-leaf', 'lee-ion-waterdrop', 'lee-ion-flame', 'lee-ion-fireball',
    'lee-ion-bonfire', 'lee-ion-umbrella', 'lee-ion-nuclear', 'lee-ion-no-smoking', 'lee-ion-thermometer', 'lee-ion-speedometer',
    'lee-ion-model-s', 'lee-ion-plane', 'lee-ion-jet', 'lee-ion-load-a', 'lee-ion-load-b', 'lee-ion-load-c', 'lee-ion-load-d',
    'lee-ion-ios-ionic-outline', 'lee-ion-ios-arrow-back', 'lee-ion-ios-arrow-forward', 'lee-ion-ios-arrow-up',
    'lee-ion-ios-arrow-right', 'lee-ion-ios-arrow-down', 'lee-ion-ios-arrow-left', 'lee-ion-ios-arrow-thin-up',
    'lee-ion-ios-arrow-thin-right', 'lee-ion-ios-arrow-thin-down', 'lee-ion-ios-arrow-thin-left', 'lee-ion-ios-circle-filled',
    'lee-ion-ios-circle-outline', 'lee-ion-ios-checkmark-empty', 'lee-ion-ios-checkmark-outline', 'lee-ion-ios-checkmark',
    'lee-ion-ios-plus-empty', 'lee-ion-ios-plus-outline', 'lee-ion-ios-plus', 'lee-ion-ios-close-empty',
    'lee-ion-ios-close-outline', 'lee-ion-ios-close', 'lee-ion-ios-minus-empty', 'lee-ion-ios-minus-outline', 'lee-ion-ios-minus',
    'lee-ion-ios-information-empty', 'lee-ion-ios-information-outline', 'lee-ion-ios-information',
    'lee-ion-ios-help-empty', 'lee-ion-ios-help-outline', 'lee-ion-ios-help', 'lee-ion-ios-search', 'lee-ion-ios-search-strong',
    'lee-ion-ios-star', 'lee-ion-ios-star-half', 'lee-ion-ios-star-outline', 'lee-ion-ios-heart', 'lee-ion-ios-heart-outline',
    'lee-ion-ios-more', 'lee-ion-ios-more-outline', 'lee-ion-ios-home', 'lee-ion-ios-home-outline', 'lee-ion-ios-cloud',
    'lee-ion-ios-cloud-outline', 'lee-ion-ios-cloud-upload', 'lee-ion-ios-cloud-upload-outline', 'lee-ion-ios-cloud-download',
    'lee-ion-ios-cloud-download-outline', 'lee-ion-ios-upload', 'lee-ion-ios-upload-outline', 'lee-ion-ios-download',
    'lee-ion-ios-download-outline', 'lee-ion-ios-refresh', 'lee-ion-ios-refresh-outline', 'lee-ion-ios-refresh-empty',
    'lee-ion-ios-reload', 'lee-ion-ios-loop-strong', 'lee-ion-ios-loop', 'lee-ion-ios-bookmarks', 'lee-ion-ios-bookmarks-outline',
    'lee-ion-ios-book', 'lee-ion-ios-book-outline', 'lee-ion-ios-flag', 'lee-ion-ios-flag-outline', 'lee-ion-ios-glasses',
    'lee-ion-ios-glasses-outline', 'lee-ion-ios-browsers', 'lee-ion-ios-browsers-outline', 'lee-ion-ios-at',
    'lee-ion-ios-at-outline', 'lee-ion-ios-pricetag', 'lee-ion-ios-pricetag-outline', 'lee-ion-ios-pricetags',
    'lee-ion-ios-pricetags-outline', 'lee-ion-ios-cart', 'lee-ion-ios-cart-outline', 'lee-ion-ios-chatboxes',
    'lee-ion-ios-chatboxes-outline', 'lee-ion-ios-chatbubble', 'lee-ion-ios-chatbubble-outline', 'lee-ion-ios-cog',
    'lee-ion-ios-cog-outline', 'lee-ion-ios-gear', 'lee-ion-ios-gear-outline', 'lee-ion-ios-settings',
    'lee-ion-ios-settings-strong', 'lee-ion-ios-toggle', 'lee-ion-ios-toggle-outline', 'lee-ion-ios-analytics',
    'lee-ion-ios-analytics-outline', 'lee-ion-ios-pie', 'lee-ion-ios-pie-outline', 'lee-ion-ios-pulse',
    'lee-ion-ios-pulse-strong', 'lee-ion-ios-filing', 'lee-ion-ios-filing-outline', 'lee-ion-ios-box',
    'lee-ion-ios-box-outline', 'lee-ion-ios-compose', 'lee-ion-ios-compose-outline', 'lee-ion-ios-trash',
    'lee-ion-ios-trash-outline', 'lee-ion-ios-copy', 'lee-ion-ios-copy-outline', 'lee-ion-ios-email',
    'lee-ion-ios-email-outline', 'lee-ion-ios-undo', 'lee-ion-ios-undo-outline', 'lee-ion-ios-redo',
    'lee-ion-ios-redo-outline', 'lee-ion-ios-paperplane', 'lee-ion-ios-paperplane-outline', 'lee-ion-ios-folder',
    'lee-ion-ios-folder-outline', 'lee-ion-ios-paper', 'lee-ion-ios-paper-outline', 'lee-ion-ios-list',
    'lee-ion-ios-list-outline', 'lee-ion-ios-world', 'lee-ion-ios-world-outline', 'lee-ion-ios-alarm',
    'lee-ion-ios-alarm-outline', 'lee-ion-ios-speedometer', 'lee-ion-ios-speedometer-outline', 'lee-ion-ios-stopwatch',
    'lee-ion-ios-stopwatch-outline', 'lee-ion-ios-timer', 'lee-ion-ios-timer-outline', 'lee-ion-ios-clock',
    'lee-ion-ios-clock-outline', 'lee-ion-ios-time', 'lee-ion-ios-time-outline', 'lee-ion-ios-calendar',
    'lee-ion-ios-calendar-outline', 'lee-ion-ios-photos', 'lee-ion-ios-photos-outline', 'lee-ion-ios-albums',
    'lee-ion-ios-albums-outline', 'lee-ion-ios-camera', 'lee-ion-ios-camera-outline', 'lee-ion-ios-reverse-camera',
    'lee-ion-ios-reverse-camera-outline', 'lee-ion-ios-eye', 'lee-ion-ios-eye-outline', 'lee-ion-ios-bolt',
    'lee-ion-ios-bolt-outline', 'lee-ion-ios-color-wand', 'lee-ion-ios-color-wand-outline', 'lee-ion-ios-color-filter',
    'lee-ion-ios-color-filter-outline', 'lee-ion-ios-grid-view', 'lee-ion-ios-grid-view-outline', 'lee-ion-ios-crop-strong',
    'lee-ion-ios-crop', 'lee-ion-ios-barcode', 'lee-ion-ios-barcode-outline', 'lee-ion-ios-briefcase',
    'lee-ion-ios-briefcase-outline', 'lee-ion-ios-medkit', 'lee-ion-ios-medkit-outline', 'lee-ion-ios-medical',
    'lee-ion-ios-medical-outline', 'lee-ion-ios-infinite', 'lee-ion-ios-infinite-outline', 'lee-ion-ios-calculator',
    'lee-ion-ios-calculator-outline', 'lee-ion-ios-keypad', 'lee-ion-ios-keypad-outline', 'lee-ion-ios-telephone',
    'lee-ion-ios-telephone-outline', 'lee-ion-ios-drag', 'lee-ion-ios-location', 'lee-ion-ios-location-outline',
    'lee-ion-ios-navigate', 'lee-ion-ios-navigate-outline', 'lee-ion-ios-locked', 'lee-ion-ios-locked-outline',
    'lee-ion-ios-unlocked', 'lee-ion-ios-unlocked-outline', 'lee-ion-ios-monitor', 'lee-ion-ios-monitor-outline',
    'lee-ion-ios-printer', 'lee-ion-ios-printer-outline', 'lee-ion-ios-game-controller-a', 'lee-ion-ios-game-controller-a-outline', 'lee-ion-ios-game-controller-b', 'lee-ion-ios-game-controller-b-outline', 'lee-ion-ios-americanfootball',
    'lee-ion-ios-americanfootball-outline', 'lee-ion-ios-baseball', 'lee-ion-ios-baseball-outline', 'lee-ion-ios-basketball', 'lee-ion-ios-basketball-outline', 'lee-ion-ios-tennisball', 'lee-ion-ios-tennisball-outline', 'lee-ion-ios-football',
    'lee-ion-ios-football-outline', 'lee-ion-ios-body', 'lee-ion-ios-body-outline', 'lee-ion-ios-person', 'lee-ion-ios-person-outline', 'lee-ion-ios-personadd', 'lee-ion-ios-personadd-outline', 'lee-ion-ios-people', 'lee-ion-ios-people-outline',
    'lee-ion-ios-musical-notes', 'lee-ion-ios-musical-note', 'lee-ion-ios-bell', 'lee-ion-ios-bell-outline', 'lee-ion-ios-mic',
    'lee-ion-ios-mic-outline', 'lee-ion-ios-mic-off', 'lee-ion-ios-volume-high', 'lee-ion-ios-volume-low', 'lee-ion-ios-play',
    'lee-ion-ios-play-outline', 'lee-ion-ios-pause', 'lee-ion-ios-pause-outline', 'lee-ion-ios-recording',
    'lee-ion-ios-recording-outline', 'lee-ion-ios-fastforward', 'lee-ion-ios-fastforward-outline', 'lee-ion-ios-rewind',
    'lee-ion-ios-rewind-outline', 'lee-ion-ios-skipbackward', 'lee-ion-ios-skipbackward-outline', 'lee-ion-ios-skipforward',
    'lee-ion-ios-skipforward-outline', 'lee-ion-ios-shuffle-strong', 'lee-ion-ios-shuffle', 'lee-ion-ios-videocam',
    'lee-ion-ios-videocam-outline', 'lee-ion-ios-film', 'lee-ion-ios-film-outline', 'lee-ion-ios-flask',
    'lee-ion-ios-flask-outline', 'lee-ion-ios-lightbulb', 'lee-ion-ios-lightbulb-outline', 'lee-ion-ios-wineglass',
    'lee-ion-ios-wineglass-outline', 'lee-ion-ios-pint', 'lee-ion-ios-pint-outline', 'lee-ion-ios-nutrition',
    'lee-ion-ios-nutrition-outline', 'lee-ion-ios-flower', 'lee-ion-ios-flower-outline', 'lee-ion-ios-rose',
    'lee-ion-ios-rose-outline', 'lee-ion-ios-paw', 'lee-ion-ios-paw-outline', 'lee-ion-ios-flame', 'lee-ion-ios-flame-outline',
    'lee-ion-ios-sunny', 'lee-ion-ios-sunny-outline', 'lee-ion-ios-partlysunny', 'lee-ion-ios-partlysunny-outline',
    'lee-ion-ios-cloudy', 'lee-ion-ios-cloudy-outline', 'lee-ion-ios-rainy', 'lee-ion-ios-rainy-outline',
    'lee-ion-ios-thunderstorm', 'lee-ion-ios-thunderstorm-outline', 'lee-ion-ios-snowy', 'lee-ion-ios-moon',
    'lee-ion-ios-moon-outline', 'lee-ion-ios-cloudy-night', 'lee-ion-ios-cloudy-night-outline', 'lee-ion-android-arrow-up',
    'lee-ion-android-arrow-forward', 'lee-ion-android-arrow-down', 'lee-ion-android-arrow-back', 'lee-ion-android-arrow-dropup',
    'lee-ion-android-arrow-dropup-circle', 'lee-ion-android-arrow-dropright', 'lee-ion-android-arrow-dropright-circle',
    'lee-ion-android-arrow-dropdown', 'lee-ion-android-arrow-dropdown-circle', 'lee-ion-android-arrow-dropleft',
    'lee-ion-android-arrow-dropleft-circle', 'lee-ion-android-add', 'lee-ion-android-add-circle', 'lee-ion-android-remove',
    'lee-ion-android-remove-circle', 'lee-ion-android-close', 'lee-ion-android-cancel', 'lee-ion-android-radio-button-off',
    'lee-ion-android-radio-button-on', 'lee-ion-android-checkmark-circle', 'lee-ion-android-checkbox-outline-blank',
    'lee-ion-android-checkbox-outline', 'lee-ion-android-checkbox-blank', 'lee-ion-android-checkbox', 'lee-ion-android-done',
    'lee-ion-android-done-all', 'lee-ion-android-menu', 'lee-ion-android-more-horizontal', 'lee-ion-android-more-vertical',
    'lee-ion-android-refresh', 'lee-ion-android-sync', 'lee-ion-android-wifi', 'lee-ion-android-call', 'lee-ion-android-apps',
    'lee-ion-android-settings', 'lee-ion-android-options', 'lee-ion-android-funnel', 'lee-ion-android-search',
    'lee-ion-android-home', 'lee-ion-android-cloud-outline', 'lee-ion-android-cloud', 'lee-ion-android-download',
    'lee-ion-android-upload', 'lee-ion-android-cloud-done', 'lee-ion-android-cloud-circle', 'lee-ion-android-favorite-outline',
    'lee-ion-android-favorite', 'lee-ion-android-star-outline', 'lee-ion-android-star-half', 'lee-ion-android-star',
    'lee-ion-android-calendar', 'lee-ion-android-alarm-clock', 'lee-ion-android-time', 'lee-ion-android-stopwatch',
    'lee-ion-android-watch', 'lee-ion-android-locate', 'lee-ion-android-navigate', 'lee-ion-android-pin',
    'lee-ion-android-compass', 'lee-ion-android-map', 'lee-ion-android-walk', 'lee-ion-android-bicycle', 'lee-ion-android-car',
    'lee-ion-android-bus', 'lee-ion-android-subway', 'lee-ion-android-train', 'lee-ion-android-boat', 'lee-ion-android-plane',
    'lee-ion-android-restaurant', 'lee-ion-android-bar', 'lee-ion-android-cart', 'lee-ion-android-camera', 'lee-ion-android-image', 'lee-ion-android-film', 'lee-ion-android-color-palette', 'lee-ion-android-create', 'lee-ion-android-mail',
    'lee-ion-android-drafts', 'lee-ion-android-send', 'lee-ion-android-archive', 'lee-ion-android-delete',
    'lee-ion-android-attach', 'lee-ion-android-share', 'lee-ion-android-share-alt', 'lee-ion-android-bookmark',
    'lee-ion-android-document', 'lee-ion-android-clipboard', 'lee-ion-android-list', 'lee-ion-android-folder-open',
    'lee-ion-android-folder', 'lee-ion-android-print', 'lee-ion-android-open', 'lee-ion-android-exit', 'lee-ion-android-contract',
    'lee-ion-android-expand', 'lee-ion-android-globe', 'lee-ion-android-chat', 'lee-ion-android-textsms',
    'lee-ion-android-hangout', 'lee-ion-android-happy', 'lee-ion-android-sad', 'lee-ion-android-person', 'lee-ion-android-people',
    'lee-ion-android-person-add', 'lee-ion-android-contact', 'lee-ion-android-contacts', 'lee-ion-android-playstore',
    'lee-ion-android-lock', 'lee-ion-android-unlock', 'lee-ion-android-microphone', 'lee-ion-android-microphone-off',
    'lee-ion-android-notifications-none', 'lee-ion-android-notifications', 'lee-ion-android-notifications-off',
    'lee-ion-android-volume-mute', 'lee-ion-android-volume-down', 'lee-ion-android-volume-up', 'lee-ion-android-volume-off',
    'lee-ion-android-hand', 'lee-ion-android-desktop', 'lee-ion-android-laptop', 'lee-ion-android-phone-portrait',
    'lee-ion-android-phone-landscape', 'lee-ion-android-bulb', 'lee-ion-android-sunny', 'lee-ion-android-alert',
    'lee-ion-android-warning', 'lee-ion-social-twitter', 'lee-ion-social-twitter-outline', 'lee-ion-social-facebook',
    'lee-ion-social-facebook-outline', 'lee-ion-social-googleplus', 'lee-ion-social-googleplus-outline', 'lee-ion-social-google',
    'lee-ion-social-google-outline', 'lee-ion-social-dribbble', 'lee-ion-social-dribbble-outline', 'lee-ion-social-octocat',
    'lee-ion-social-github', 'lee-ion-social-github-outline', 'lee-ion-social-instagram', 'lee-ion-social-instagram-outline',
    'lee-ion-social-whatsapp', 'lee-ion-social-whatsapp-outline', 'lee-ion-social-snapchat', 'lee-ion-social-snapchat-outline',
    'lee-ion-social-foursquare', 'lee-ion-social-foursquare-outline', 'lee-ion-social-pinterest', 'lee-ion-social-pinterest-outline',
    'lee-ion-social-rss', 'lee-ion-social-rss-outline', 'lee-ion-social-tumblr', 'lee-ion-social-tumblr-outline',
    'lee-ion-social-wordpress', 'lee-ion-social-wordpress-outline', 'lee-ion-social-reddit', 'lee-ion-social-reddit-outline',
    'lee-ion-social-hackernews', 'lee-ion-social-hackernews-outline', 'lee-ion-social-designernews', 'lee-ion-social-designernews-outline',
    'lee-ion-social-yahoo', 'lee-ion-social-yahoo-outline', 'lee-ion-social-buffer', 'lee-ion-social-buffer-outline', 'lee-ion-social-skype',
    'lee-ion-social-skype-outline', 'lee-ion-social-linkedin', 'lee-ion-social-linkedin-outline', 'lee-ion-social-vimeo',
    'lee-ion-social-vimeo-outline', 'lee-ion-social-twitch', 'lee-ion-social-twitch-outline', 'lee-ion-social-youtube',
    'lee-ion-social-youtube-outline', 'lee-ion-social-dropbox', 'lee-ion-social-dropbox-outline', 'lee-ion-social-apple',
    'lee-ion-social-apple-outline', 'lee-ion-social-android', 'lee-ion-social-android-outline', 'lee-ion-social-windows',
    'lee-ion-social-windows-outline', 'lee-ion-social-html5', 'lee-ion-social-html5-outline', 'lee-ion-social-css3',
    'lee-ion-social-css3-outline', 'lee-ion-social-javascript', 'lee-ion-social-javascript-outline', 'lee-ion-social-angular',
    'lee-ion-social-angular-outline', 'lee-ion-social-nodejs', 'lee-ion-social-sass', 'lee-ion-social-python', 'lee-ion-social-chrome',
    'lee-ion-social-chrome-outline', 'lee-ion-social-codepen', 'lee-ion-social-codepen-outline', 'lee-ion-social-markdown',
    'lee-ion-social-tux', 'lee-ion-social-freebsd-devil', 'lee-ion-social-usd', 'lee-ion-social-usd-outline', 'lee-ion-social-bitcoin',
    'lee-ion-social-bitcoin-outline', 'lee-ion-social-yen', 'lee-ion-social-yen-outline', 'lee-ion-social-euro', 'lee-ion-social-euro-outline'];

var iconimages = [
     'icon-add-missing-members ', 'icon-add-small ', 'icon-add-thin ', 'icon-add-user ', 'icon-add-white ', 'icon-add ', 'icon-admin ', 'icon-arrow-down ', 'icon-arrow-forward ', 'icon-arrow-up ', 'icon-attachment ', 'icon-audio-off ', 'icon-audio-on ', 'icon-back-query-results ', 'icon-branch-locked ', 'icon-branch ', 'icon-calendar ', 'icon-charts-area ', 'icon-charts-bar ', 'icon-charts-column ', 'icon-charts-line ', 'icon-charts-pie ', 'icon-charts-pivotchart ', 'icon-charts-pivottable ', 'icon-chat-mention-white ', 'icon-chat-mention ', 'icon-check ', 'icon-close ', 'icon-comment-add ', 'icon-comment-next ', 'icon-comment-prev ', 'icon-comment ', 'icon-commented-file ', 'icon-compare ', 'icon-copy-text ', 'icon-dashboard-white ', 'icon-delete-f1-background ', 'icon-delete-grey-f1-background ', 'icon-delete-user ', 'icon-delete-white ', 'icon-delete ', 'icon-discussion-adornment ', 'icon-document ', 'icon-dot ', 'icon-down-gray ', 'icon-down ', 'icon-drop-left ', 'icon-drop-right ', 'icon-drop ', 'icon-edit-f1-background ', 'icon-edit-grey-f1-background ', 'icon-edit ', 'icon-editor-font-bold ', 'icon-editor-font-italic ', 'icon-editor-font-underline ', 'icon-editor-indent ', 'icon-editor-list-bullet ', 'icon-editor-list-number ', 'icon-editor-outdent ', 'icon-editor-picture ', 'icon-ellipsis-white ', 'icon-ellipsis ', 'icon-empty ', 'icon-enter-full-screen ', 'icon-envelope ', 'icon-error-exclamation ', 'icon-exit-full-screen ', 'icon-export ', 'icon-favorite-in ', 'icon-favorite-out ', 'icon-filter ', 'icon-folder-open ', 'icon-folder-white ', 'icon-folder ', 'icon-font-color ', 'icon-form-group-collapsed ', 'icon-form-group-expanded ', 'icon-git-logo ', 'icon-header-help ', 'icon-header-settings ', 'icon-help ', 'icon-history ', 'icon-home ', 'icon-info-white ', 'icon-info ', 'icon-invalid-field ', 'icon-new-document ', 'icon-new-folder ', 'icon-new ', 'icon-next-2 ', 'icon-next ', 'icon-notifications ', 'icon-open-visualstudio ', 'icon-open-white ', 'icon-open ', 'icon-pause ', 'icon-people ', 'icon-pin ', 'icon-play ', 'icon-prev-2 ', 'icon-prev ', 'icon-process-branch ', 'icon-process-custom ', 'icon-process-system ', 'icon-project-white ', 'icon-queue-build ', 'icon-refresh ', 'icon-rename ', 'icon-restricted-2 ', 'icon-save-all ', 'icon-save-as ', 'icon-save-close ', 'icon-save ', 'icon-search ', 'icon-settings ', 'icon-social-facebook ', 'icon-social-twitter ', 'icon-sort-asc-1 ', 'icon-sort-asc ', 'icon-sort-desc ', 'icon-sort ', 'icon-submodule-external ', 'icon-submodule ', 'icon-tfs-bug ', 'icon-tfs-build-reason-batchedci ', 'icon-tfs-build-reason-checkinshelveset ', 'icon-tfs-build-reason-header ', 'icon-tfs-build-reason-schedule ', 'icon-tfs-build-reason-scheduleforced ', 'icon-tfs-build-reason-validateshelveset ', 'icon-tfs-build-retain-header ', 'icon-tfs-build-status-canceled ', 'icon-tfs-build-status-failed ', 'icon-tfs-build-status-header ', 'icon-tfs-build-status-inprogress ', 'icon-tfs-build-status-partiallysucceeded ', 'icon-tfs-build-status-postponed ', 'icon-tfs-build-status-queued ', 'icon-tfs-build-status-stopped ', 'icon-tfs-build-status-succeeded ', 'icon-tfs-build ', 'icon-tfs-changelist ', 'icon-tfs-clause-group ', 'icon-tfs-clause-ungroup ', 'icon-tfs-home-newitem ', 'icon-tfs-left-halo ', 'icon-tfs-left ', 'icon-tfs-link-add ', 'icon-tfs-link-delete ', 'icon-tfs-link ', 'icon-tfs-microsoft-requirementcategory ', 'icon-tfs-play-small ', 'icon-tfs-process-guidance ', 'icon-tfs-project-portal ', 'icon-tfs-query-edit ', 'icon-tfs-query-flat ', 'icon-tfs-query-new ', 'icon-tfs-query-onehop ', 'icon-tfs-query-run ', 'icon-tfs-query-tree ', 'icon-tfs-release-draft ', 'icon-tfs-release-notstarted ', 'icon-tfs-reports ', 'icon-tfs-requirement ', 'icon-tfs-right-halo ', 'icon-tfs-right ', 'icon-tfs-task ', 'icon-tfs-tcm-active-small ', 'icon-tfs-tcm-active-test ', 'icon-tfs-tcm-add-attachment ', 'icon-tfs-tcm-associated-pane-toggle ', 'icon-tfs-tcm-attach-white ', 'icon-tfs-tcm-block-test ', 'icon-tfs-tcm-blocked-small ', 'icon-tfs-tcm-bug-white ', 'icon-tfs-tcm-create-shared-steps ', 'icon-tfs-tcm-down-blue ', 'icon-tfs-tcm-down-white ', 'icon-tfs-tcm-drop-white ', 'icon-tfs-tcm-edit-test ', 'icon-tfs-tcm-edit ', 'icon-tfs-tcm-export-html ', 'icon-tfs-tcm-fail-step-grey ', 'icon-tfs-tcm-failed-small ', 'icon-tfs-tcm-insert-parameter ', 'icon-tfs-tcm-insert-shared-steps ', 'icon-tfs-tcm-insert-step-white ', 'icon-tfs-tcm-insert-step ', 'icon-tfs-tcm-mtm ', 'icon-tfs-tcm-not-applicable-small ', 'icon-tfs-tcm-not-applicable ', 'icon-tfs-tcm-open-in-new-tab ', 'icon-tfs-tcm-pass-step-grey ', 'icon-tfs-tcm-passed-small ', 'icon-tfs-tcm-pause-small ', 'icon-tfs-tcm-query-based-suite ', 'icon-tfs-tcm-requirement-based-suite ', 'icon-tfs-tcm-reset-active ', 'icon-tfs-tcm-resume-test ', 'icon-tfs-tcm-save-close-white ', 'icon-tfs-tcm-save-white ', 'icon-tfs-tcm-shared-step ', 'icon-tfs-tcm-static-suite ', 'icon-tfs-tcm-test-no-outcome ', 'icon-tfs-tcm-test-plan ', 'icon-tfs-tcm-tra-create-bug ', 'icon-tfs-tcm-tra-needs-investigation ', 'icon-tfs-tcm-tra-result-aborted ', 'icon-tfs-tcm-tra-result-error ', 'icon-tfs-tcm-tra-result-failed ', 'icon-tfs-tcm-tra-result-in-progress ', 'icon-tfs-tcm-tra-result-not-executed ', 'icon-tfs-tcm-tra-result-passed ', 'icon-tfs-tcm-tra-result-warning ', 'icon-tfs-tcm-tra-run-unspecified ', 'icon-tfs-tcm-tra-update-analysis ', 'icon-tfs-tcm-tra-waiting ', 'icon-tfs-tcm-up-white ', 'icon-tfs-vc-new-pullrequest ', 'icon-tfs-vc-pullrequests-abandoned ', 'icon-tfs-vc-pullrequests-code-comment ', 'icon-tfs-vc-pullrequests-merge ', 'icon-tfs-vc-pullrequests-merged-status-indicator ', 'icon-tfs-vc-pullrequests-ref-update ', 'icon-tfs-vc-status-failed ', 'icon-tfs-vc-status-processing ', 'icon-tfs-vc-status-succeeded ', 'icon-tfs-vc-status-waiting-response-transparent ', 'icon-tfs-vc-status-waiting-transparent ', 'icon-tfs-vc-status-waiting ', 'icon-tfs-work-item-copy ', 'icon-tfs-work-item-new-linked ', 'icon-tfs-work-item ', 'icon-tick ', 'icon-toggle-button-horizontal-collapsed ', 'icon-toggle-button-horizontal-expanded ', 'icon-tree-collapse-all ', 'icon-tree-collapsed ', 'icon-tree-corner ', 'icon-tree-expand-all ', 'icon-tree-expand-one-level ', 'icon-tree-expanded ', 'icon-tree ', 'icon-trial-white ', 'icon-undo ', 'icon-unpin ', 'icon-up ', 'icon-valid-field ', 'icon-warning ', 'icon-wide-tree-collapsed ', 'icon-wide-tree-expanded ', 'icon-window ', 'icon-wit-attachments ', 'icon-wit-classicview ', 'icon-wit-history ', 'icon-AddRow', 'icon-Analyze', 'icon-AppendChild', 'icon-AppendSibling', 'icon-ApproveLog', 'icon-AttachmentManage', 'icon-Audit', 'icon-BizLog', 'icon-CancelSubmit', 'icon-Check', 'icon-Clear', 'icon-Close', 'icon-Collapse', 'icon-CollapseAll', 'icon-Confirm', 'icon-Copy', 'icon-CopyRow', 'icon-Create', 'icon-Delete', 'icon-DeleteColumn', 'icon-DeleteRow', 'icon-DeselectAll', 'icon-Disassemble', 'icon-Edit', 'icon-Email', 'icon-Enable', 'icon-Expand', 'icon-ExpandAll', 'icon-Expire', 'icon-Export', 'icon-ExportExcel', 'icon-Filter', 'icon-Find', 'icon-First', 'icon-Help', 'icon-History', 'icon-Import', 'icon-InsertColumn', 'icon-InsertColumns', 'icon-InsertRow', 'icon-Last', 'icon-Lock', 'icon-Message', 'icon-MoveAllLeft', 'icon-MoveAllRight', 'icon-MoveButtom', 'icon-MoveLeft', 'icon-MoveRight', 'icon-MoveTop', 'icon-New', 'icon-NewFolder', 'icon-Next', 'icon-Open', 'icon-PageSetting', 'icon-ParentDirectory', 'icon-Paste', 'icon-Previous', 'icon-Print', 'icon-Priview', 'icon-ProcessView', 'icon-Quit', 'icon-Refresh', 'icon-Replace', 'icon-Reset', 'icon-Restore', 'icon-Save', 'icon-SaveAndNew', 'icon-SaveAs', 'icon-SelectAll', 'icon-SequenceCheck', 'icon-Setting', 'icon-SpeedLocation', 'icon-Submit', 'icon-Synchronization', 'icon-TemporarySave', 'icon-TreeCollapse', 'icon-TreeDetail', 'icon-Unlock', 'icon-View', 'icon-approve', 'icon-attr', 'icon-checked', 'icon-search', 'icon-star', 'icon-star2', 'icon-Disable', 'icon-unchecked', 'icon-ViewProcess'
];