2017-11-01 22:25:27,406 [12] ERROR FormBuilder.Service.FBDataModelService - 列“EndTime”不属于表 PurExpert。
System.ArgumentException: 列“EndTime”不属于表 PurExpert。
   在 System.Data.DataRow.GetDataColumn(String columnName)
   在 System.Data.DataRow.get_Item(String columnName)
   在 FormBuilder.Service.DataModelEngine.BuildUpdateSql(FBDataModelObjects obj, DataSet ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelEngine.cs:行号 177
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 651
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:26:55,697 [12] ERROR FormBuilder.Service.FBDataModelService - 列“EndTime”不属于表 PurExpert。
System.ArgumentException: 列“EndTime”不属于表 PurExpert。
   在 System.Data.DataRow.GetDataColumn(String columnName)
   在 System.Data.DataRow.get_Item(String columnName)
   在 FormBuilder.Service.DataModelEngine.BuildUpdateSql(FBDataModelObjects obj, DataSet ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelEngine.cs:行号 177
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 651
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:27:49,180 [21] ERROR FormBuilder.Service.FBDataModelService - 列“EndTime”不属于表 PurExpert。
System.ArgumentException: 列“EndTime”不属于表 PurExpert。
   在 System.Data.DataRow.GetDataColumn(String columnName)
   在 System.Data.DataRow.get_Item(String columnName)
   在 FormBuilder.Service.DataModelEngine.BuildUpdateSql(FBDataModelObjects obj, DataSet ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelEngine.cs:行号 177
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 651
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:30:06,815 [26] ERROR FormBuilder.Service.FBDataModelService - 序列不包含任何元素
System.InvalidOperationException: 序列不包含任何元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 647
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:31:04,242 [27] ERROR FormBuilder.Service.FBDataModelService - 序列不包含任何元素
System.InvalidOperationException: 序列不包含任何元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 647
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:36:09,526 [39] ERROR FormBuilder.Service.FBDataModelService - 序列不包含任何元素
System.InvalidOperationException: 序列不包含任何元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 653
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:36:14,199 [39] ERROR FormBuilder.Service.FBDataModelService - 序列不包含任何元素
System.InvalidOperationException: 序列不包含任何元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 653
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-01 22:37:29,470 [39] ERROR FormBuilder.Service.FBDataModelService - 序列不包含任何元素
System.InvalidOperationException: 序列不包含任何元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 653
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
