2017-11-13 17:14:39,643 [30] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:14:44,900 [33] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:14:59,469 [33] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:17:05,231 [12] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:18:01,139 [30] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:18:19,444 [30] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 17:19:41,228 [30] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
2017-11-13 21:33:00,653 [28] ERROR FormBuilder.Service.FBDataModelService - 未找到列 [id]。
System.Data.EvaluateException: 未找到列 [id]。
   在 System.Data.NameNode.Bind(DataTable table, List`1 list)
   在 System.Data.BinaryNode.Bind(DataTable table, List`1 list)
   在 System.Data.DataExpression.Bind(DataTable table)
   在 System.Data.Select..ctor(DataTable table, String filterExpression, String sort, DataViewRowState recordStates)
   在 System.Data.DataTable.Select(String filterExpression)
   在 FormBuilder.Service.DataModelCom.saveFileList(String modelID, String dataID, DataSet ds, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 718
   在 FormBuilder.Service.DataModelCom.saveModelALL(String modelID, FBDataModel model, String dataID, DataSet ds, String status, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 629
   在 FormBuilder.Service.FBDataModelService.saveModelALL(String modelID, String dataID, DataSet ds, String status) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 767
