2017-10-13 00:29:20,086 [11] ERROR FormBuilder.Service.FBDataModelService - 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 FormBuilder.Service.DMTreeHelper.getMaxPath(FBDataModelObjects objectModel, String path, String level, Boolean isSame, DataSet& ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 70
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 493
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 683
2017-10-13 00:29:34,065 [11] ERROR FormBuilder.Service.FBDataModelService - 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 FormBuilder.Service.DMTreeHelper.getMaxPath(FBDataModelObjects objectModel, String path, String level, Boolean isSame, DataSet& ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 70
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 493
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 683
2017-10-13 00:30:27,723 [28] ERROR FormBuilder.Service.FBDataModelService - 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 FormBuilder.Service.DMTreeHelper.getMaxPath(FBDataModelObjects objectModel, String path, String level, Boolean isSame, DataSet& ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 70
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 493
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 683
2017-10-13 00:32:59,775 [24] ERROR FormBuilder.Service.FBDataModelService - 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 FormBuilder.Service.DMTreeHelper.getMaxPath(FBDataModelObjects objectModel, String path, String level, Boolean isSame, DataSet& ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 70
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 493
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 683
2017-10-13 00:33:44,614 [24] ERROR FormBuilder.Service.FBDataModelService - 未将对象引用设置到对象的实例。
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 FormBuilder.Service.DMTreeHelper.getMaxPath(FBDataModelObjects objectModel, String path, String level, Boolean isSame, DataSet& ds) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 70
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 493
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 683
