2018-05-13 15:45:41,163 [5] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 70
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field, String typecode) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 61
