2018-05-07 23:06:08,423 [12] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 65
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 60
2018-05-07 23:07:34,823 [13] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 65
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 60
2018-05-07 23:11:27,531 [24] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 65
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 60
2018-05-07 23:13:40,749 [13] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 65
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 60
2018-05-07 23:20:11,077 [13] ERROR FormBuilder.Web.Areas.FormBuilder.Controllers.DataModelController - System.NotImplementedException: 未实现该方法或操作。
   在 FormBuilder.Service.FBFileService.saveFile(FBFileSave model, Byte[] data) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\CustomForm\FBFileService.cs:行号 65
   在 FormBuilder.Web.Areas.FormBuilder.Controllers.FileController.Upload(String dataID, String frmID, String field) 位置 F:\Project\FormBuilder\Com.FormBuilder\FormBuilder.Web\Areas\FormBuilder\Controllers\FileController.cs:行号 60
