2017-11-09 11:25:23,975 [23] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:32,442 [33] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:35,425 [23] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:41,065 [8] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:45,644 [8] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:48,873 [23] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:51,506 [26] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:53,755 [33] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:56,193 [33] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:25:57,956 [33] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:27:47,089 [10] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:28:53,504 [8] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 11:49:22,594 [25] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'Disable' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'Disable' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 504
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:12:58,346 [30] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:13:28,081 [22] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:22:24,979 [13] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:22:46,007 [27] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:23:18,837 [27] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:24:08,897 [25] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
2017-11-09 17:26:25,551 [27] ERROR FormBuilder.Service.FBDataModelService - Data too long for column 'IsDetail' at row 1
MySql.Data.MySqlClient.MySqlException (0x80004005): Data too long for column 'IsDetail' at row 1
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   在 MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   在 NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   在 NPoco.Database.Execute(Sql Sql)
   在 FormBuilder.Service.DMTreeHelper.updateMXField(FBDataModelObjects objectModel, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DMTreeHelper.cs:行号 104
   在 FormBuilder.Service.DataModelCom.saveModel(String modelID, FBDataModel model, DataSet ds, String status, TreeNode treeNode, Database Db) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\DM.Com\DataModelCom.cs:行号 519
   在 FormBuilder.Service.FBDataModelService.saveModel(String modelID, DataSet ds, String status, TreeNode tree) 位置 F:\Project\FormBuilder\Com.FormBuilder\FromBuilder.Service\FBDataModelService.cs:行号 746
